### ISSUE TITLE
Getting error while integrating with angular 8 lazy load modules.

### ISSUE THREAD

**Issue by BhanuTejP** [imagekit-developer/imagekit-angular#10]
Hi, 
I'm trying to integrate image-kit with my angular 8 app.

I followed the documentation for setting up the things.

It is working well if I use `<ik-image src="my-img-url" alt="This is an alt"></ik-image>` in app.component.html but I'm getting the following error if I use it in my lazy loading module components.
![image](https://user-images.githubusercontent.com/40133297/80569690-13d79d80-8a17-11ea-9262-0681a1851f88.png)

To deal with this error,  I moved the below code /import to my shared module.
 
  ImagekitioAngularModule.forRoot({
      publicKey: environment.publicKey,
      urlEndpoint: environment.urlEndpoint,
      authenticationEndpoint: environment.authenticationEndpoint + 'image_kit/auth'
    }),

But Im getting the below error.

![image](https://user-images.githubusercontent.com/40133297/80570056-bf80ed80-8a17-11ea-8041-2c8764ef8828.png)

So can you please tell me what I am doing wrong/ missing here.

Thank you.

**Comment by imagekitio** [comment]
Hi @BhanuTejP 

Can you please test with the latest version 1.0.1?

**Comment by hishamhafeel** [comment]
@imagekitio I also got the same error. If it is imported in AppModule, then I am unable to use it in another module. I also cant import it in multiple modules. 
I have used   "imagekitio-angular": "^1.0.1" in package.json.

Can you please give a solution for this. 
Thank you

**Comment by violetviolinist** [comment]
@BhanuTejP 
@hishamhafeel 
Sorry for the day. The issue has been fixed. You can now import the ImageKit module in lazy modules just like you would in the App module:

`@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    LazyRoutingModule,
    ImagekitioAngularModule.forRoot({
      urlEndpoint: "URL_ENDPOINT",
      publicKey: "PUBLIC_KEY",
      authenticationEndpoint: "AUTH_ENDPOINT"
    }),
  ]
})
export class LazyModule { }`
