### ISSUE TITLE
Functionality to pass in loading lazy

### ISSUE THREAD

**Issue by flashjpr** [imagekit-developer/imagekit-angular#21]
At the moment, there is no way to pass the loading="lazy" attribute for lazy loading. 
Expose an Input() on the ik-image component to allow passing such input.

https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

**Comment by tiboprea** [comment]
It would be great to have this functionality. I've been trying to find a workaround but I couldn't.

**Comment by flashjpr** [comment]
Any update on this? Are you planning to support it? Do you accept a PR if we do it?

**Comment by imagekitio** [comment]
Hi Alex, we will be releasing a new version of this SDK in around 8 weeks with the aim to solve these issues and improve developer experience.

**Comment by imagekitio** [comment]
Fixed in version 2.0.0.
