### ISSUE TITLE
Will this work with Angular 15.

### ISSUE THREAD

**Issue by JohnFredMeyer** [imagekit-developer/imagekit-angular#42]
In the preliminary phases of looking at image kit as solution for product I’m working on. Curious if this will work with the latest version of angular.

**Comment by imagekitio** [comment]
@JohnFredMeyer there is PR in review that will work with latest version of Angular.

**Comment by JohnFredMeyer** [comment]
@imagekitio thanks for the update. Also after some research is there any reason to use ik-image over ngoptimized image? appears there is already a builder in angular for imagekit io and ngoptimized image as of angular 14.2.

**Comment by imagekitio** [comment]
Because we have custom functionality for lazy loading and low quality image placeholder

**Comment by JohnFredMeyer** [comment]
@imagekitio thanks. Will setup account and get started. Will keep eye out on PR. thanks again!
