### ISSUE TITLE
Angular Version 9 Support

### ISSUE THREAD

**Issue by jneterer** [imagekit-developer/imagekit-angular#9]
Hello,

I am interested in moving from Cloudinary to Imagekit, however Imagekit does not have support for Angular version 9. I tried using it in my Angular 9 application, but I am running into various issues. One of which is the following:

> ERROR in ./node_modules/imagekitio-angular/__ivy_ngcc__/imagekitio-angular.js
Module not found: Error: Can't resolve '../../package.json' in '/angular-starters/node_modules/imagekitio-angular/__ivy_ngcc__'

Do you know if there are plans to upgrade the library to support Angular 9? If so, when could I expect that to be complete?

Thanks,

Jacob Neterer

**Comment by jneterer** [comment]
Hello,

Any thoughts on this one?

Thanks,

Jacob

**Comment by jneterer** [comment]
Hello,

Any updates on the progress of this issue?

Thanks!

Jacob

**Comment by imagekitio** [comment]
Hi @jneterer 

The latest version 1.0.1 should work with Angular 9. Please check it out.

Here is the sample application for Angular 9 - https://github.com/imagekit-developer/imagekit-angular/tree/master/samples/imagekitio-angular9-sample

Thanks
Manu
